### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by buckett** [thesgc/chembiohub_ws#1]
I was following you're instructions (in the README) to get a copy of chembiohub started and it seems that when running `vagrant up` I got the following error:
```
==> default: bower ESUDO         Cannot be run with sudo
==> default: 
==> default: Additional error details:
==> default: Since bower is a user command, there is no need to execute it with superuser permissions.
==> default: If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
==> default: 
==> default: http://www.joyent.com/blog/installing-node-and-npm
==> default: https://gist.github.com/isaacs/579814
==> default: 
==> default: You can however run a command with sudo using --allow-root option
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by strets123** [comment]
Thanks for that Matthew, turns out that I need to update the base box. I will get back to you tomorrow with a fix on this.

And yes, my confidence was misplaced :)

**Comment by buckett** [comment]
Is the script to build the base box in the repositories somewhere?

**Comment by strets123** [comment]
Yes, the script is here but is not linked to vagrant and takes 40 mins to run due to the cheminformatics packages compilation time.

https://github.com/thesgc/chembiohub_ws/tree/master/scripts

I have changed the box URL to a new version which now works.

For live reload you will need to install grunt and bower locally which you probably already have.

**Comment by buckett** [comment]
I'm now getting a 404 when attempting to download a copy of the box:
```
==> default: Adding box 'http://staging.chembiohub.ox.ac.uk/all_deps.box' (v0) for provider: virtualbox    default: Downloading: http://staging.chembiohub.ox.ac.uk/all_deps.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

**Comment by strets123** [comment]
Sorry again, I didn't update the URL in the vagrantfile, pull and try again.

This is a really useful exercise by the way. 
I need to validate this stuff a lot better. 
I have added the login URL and the project adding part.

Currently the angular app is completely separate from django app, thinking that under webauth this is OK security wise. Security is at the webservice level. It should redirect to the login page if you log out.

Cheers,
A

**Comment by strets123** [comment]
I have been working on changes to the DB today. These are now all committed and pushed so by running

     git pull
     git submodule update --recursive

You should get a codebase consistent with the database in the vagrant box

I clearly need to have a blank box to start from - I did before but just upgraded Django on a legacy project so got complicated...

**Comment by buckett** [comment]
Thanks, box downloads now and starts up, however when I attempt to start python I get:
```
(chembiohub_ws)vagrant@ubuntu:~$ cd chembiohub_ws/
(chembiohub_ws)vagrant@ubuntu:~/chembiohub_ws$ python manage.py runserver 0.0.0.0:8000
/home/vagrant/chembiohub_ws/src/chembl_core_db/chembl_core_db/__init__.py:3: UserWarning: Unbuilt egg for chembl-beaker [unknown version] (/home/vagrant/chembiohub_ws/src/chembl_beaker)
  __version__ = __import__('pkg_resources').get_distribution('chembl_core_db').version

/home/vagrant/chembiohub_ws/src/chembl_core_model/chembl_core_model/__init__.py:4: UserWarning: Unbuilt egg for chembl-beaker [unknown version] (/home/vagrant/chembiohub_ws/src/chembl_beaker)
  __version__ = __import__('pkg_resources').get_distribution('chembl_core_model').version

/home/vagrant/chembiohub_ws/src/chembl_business_model/chembl_business_model/__init__.py:4: UserWarning: Unbuilt egg for chembl-beaker [unknown version] (/home/vagrant/chembiohub_ws/src/chembl_beaker)
  __version__ = __import__('pkg_resources').get_distribution('chembl_business_model').version

/home/vagrant/chembiohub_ws/src/chembl_core_db/chembl_core_db/db/customManagers.py:74: RemovedInDjango18Warning: `CompoundMolsManager.get_query_set` method should be renamed `get_queryset`.
  class CompoundMolsManager(models.Manager, CompoundMolsMixin):

/home/vagrant/chembiohub_ws/src/chembl_core_db/chembl_core_db/db/customManagers.py:109: RemovedInDjango18Warning: `MoleculeDictionaryManager.get_query_set` method should be renamed `get_queryset`.
  class MoleculeDictionaryManager(models.Manager, MoleculeDictionaryMixin):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/vagrant/miniconda/envs/chembiohub_ws/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/chembiohub_ws/src/chembl_business_model/chembl_business_model/models/__init__.py", line 8, in <module>
    from chembl_business_model.models.compounds import *
  File "/home/vagrant/chembiohub_ws/src/chembl_business_model/chembl_business_model/models/compounds.py", line 15, in <module>
    from chembl_business_model.utils import inchiFromPipe
  File "/home/vagrant/chembiohub_ws/src/chembl_business_model/chembl_business_model/utils.py", line 9, in <module>
    from indigoWrapper import *
  File "/home/vagrant/chembiohub_ws/src/chembl_business_model/chembl_business_model/indigoWrapper.py", line 3, in <module>
    import indigo
ImportError: No module named indigo
```

**Comment by strets123** [comment]
Sorry, pull again, 

    vagrant halt

    vagrant up --provision

I have commented out too many things in the provision file.

**Comment by strets123** [comment]
Hi, I have seen an error on sentry which I belive comes from your side about chembl_webservices.

Sounds like the github repos may have got stuck on an earlier revision at your end. You will have to run 

     
     git submodule foreach git checkout master
     git submodule foreach git pull 

Not sure why it did this but perhaps the earlier submodule update didn't work
